-- Run inside bmv_quant.
-- This script creates the project tables if they do not exist
-- and applies additive migrations for older versions.


-- =========================================================
-- Assets
-- =========================================================

CREATE TABLE IF NOT EXISTS public.assets (
    asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code TEXT NOT NULL,
    base_symbol TEXT NOT NULL,
    series TEXT NOT NULL,
    market_code TEXT,

    company_name TEXT,

    asset_type TEXT NOT NULL CHECK (
        asset_type IN (
            'STOCK',
            'ETF',
            'FUND',
            'UNKNOWN'
        )
    ),

    actinver_symbol TEXT NOT NULL,
    yahoo_symbol TEXT NOT NULL,

    data_available BOOLEAN NOT NULL DEFAULT FALSE,

    history_refreshed_on DATE,

    CONSTRAINT assets_base_series_key
        UNIQUE (base_symbol, series)
);


-- =========================================================
-- Prices
-- =========================================================

CREATE TABLE IF NOT EXISTS public.prices (
    date DATE NOT NULL,

    asset_id BIGINT NOT NULL
        REFERENCES public.assets(asset_id),

    open DOUBLE PRECISION NOT NULL,
    high DOUBLE PRECISION NOT NULL,
    low DOUBLE PRECISION NOT NULL,
    close DOUBLE PRECISION NOT NULL,

    adjusted_close DOUBLE PRECISION,

    volume BIGINT NOT NULL
        CHECK (volume >= 0),

    quality_flags TEXT NOT NULL DEFAULT '',

    PRIMARY KEY (
        asset_id,
        date
    )
);


-- =========================================================
-- Price rejections
-- =========================================================

CREATE TABLE IF NOT EXISTS public.price_rejections (
    rejection_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    asset_id BIGINT NOT NULL
        REFERENCES public.assets(asset_id),

    date DATE,

    yahoo_symbol TEXT NOT NULL,

    reason TEXT NOT NULL,

    created_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- Additive migrations
-- =========================================================

ALTER TABLE public.assets
ADD COLUMN IF NOT EXISTS
    history_refreshed_on DATE;


ALTER TABLE public.prices
ADD COLUMN IF NOT EXISTS
    adjusted_close DOUBLE PRECISION;


ALTER TABLE public.prices
ADD COLUMN IF NOT EXISTS
    quality_flags TEXT NOT NULL DEFAULT '';

-- Older rejection tables did not store the provider symbol.
ALTER TABLE public.price_rejections
ADD COLUMN IF NOT EXISTS yahoo_symbol TEXT;

UPDATE public.price_rejections AS r
SET yahoo_symbol = a.yahoo_symbol
FROM public.assets AS a
WHERE r.asset_id = a.asset_id AND r.yahoo_symbol IS NULL;

CREATE INDEX IF NOT EXISTS price_rejections_asset_date_idx
ON public.price_rejections (asset_id, date);
